/* =====================================================================
   FAIND — testi delle pagine tematiche in inglese, francese e tedesco
   (l'italiano è in topics.mjs). Stessa struttura per ogni tema:
   slug, name, short, title, desc, lede, body [[titolo, paragrafo]…],
   watch […], faq [[domanda, risposta]…]
   ===================================================================== */

export const TOPICS_I18N = {
  en: {
    robot: {
      slug: 'humanoid-robots', name: 'Robotics & humanoids', short: 'robots and humanoids',
      title: 'Robots and humanoids: news, videos and where things stand',
      desc: 'Humanoid robots, self-driving cars, drones and robots in space: news updated every hour with the source, videos and the FAIND timeline.',
      lede: 'From humanoid robots learning to move around warehouses to driverless cars, from drones to rovers in space: here FAIND collects, hour by hour, what happens where artificial intelligence meets the physical world.',
      body: [
        ['Why everyone is talking about it now', 'For decades robots stayed inside factories, repeating the same movement behind a safety cage. What is new is that AI models, the same ones that learned to understand text and images, are now used to let a machine <strong>see, understand and act</strong> in places that were not prepared for it. That is why companies such as Tesla, Figure, Unitree and Boston Dynamics are showing humanoids that walk, grasp objects and carry out simple tasks.'],
        ['Humanoids: between demos and reality', 'A polished video is not yet a product. The questions to ask about every announcement are always the same: is the robot acting on its own or being remotely controlled? How long does the battery last? What does it cost, and who is really using it outside the lab? For now the first concrete uses are in logistics and on production lines, where tasks are repetitive and the environment is controlled. The home, full of surprises, remains the hardest goal.'],
        ['Not only humanoids', 'The robotics that already works often looks less spectacular: robotaxis carrying passengers without a driver in some cities, drones for deliveries and inspections, surgical robots guided by the doctor, arms in warehouses, rovers and satellites that decide for themselves because they are too far away to be steered. Following all of it together helps to see where the technology is mature and where it is still a promise.']
      ],
      watch: ['new humanoid models and their first real uses in factories and warehouses', 'autonomous driving: robotaxis, permits, accidents and rules', 'drones, home robots and care robots', 'robotics in space, at sea and in agriculture'],
      faq: [
        ['What is a humanoid robot?', 'It is a robot shaped roughly like a person, usually with two legs, two arms and hands able to grasp objects. The idea is that it can move and work in places built for people, without having to change them.'],
        ['Are humanoid robots already on sale?', 'Some models can be bought by companies and research centres, and a few makers have announced versions for the public. For the most part, though, these are still pilot projects in factories and warehouses: prices, battery life and reliability vary a lot from one announcement to the next, which is why it pays to follow the news with the source.'],
        ['What is the difference between a robot and artificial intelligence?', 'Artificial intelligence is the software that recognises, predicts and decides; the robot is the machine that acts in the physical world. A robot can work without AI by repeating programmed movements; AI lets it adapt to situations nobody planned for.'],
        ['Do self-driving cars really exist?', 'Yes: in some cities around the world, robotaxi services run with no driver on board, within set areas and conditions. Fully autonomous driving everywhere and in any weather is not yet a reality.'],
        ['Will robots take people\'s jobs?', 'They mainly automate repetitive, tiring or dangerous tasks, which changes jobs more than it wipes them all out at once. The effects depend on the sector and on how fast robots are adopted: FAIND also follows this on its AI and work page.']
      ]
    },
    domus: {
      slug: 'ai-at-home', name: 'Domus: AI at home', short: 'AI at home',
      title: 'AI at home: smartphones, smart home and appliances',
      desc: 'Artificial intelligence in everyday objects: smartphones, voice assistants, smart home, TVs and appliances. News with the source, videos and timeline.',
      lede: 'Domus is Latin for home. On this page FAIND follows the artificial intelligence that enters everyday objects: the phone in your pocket, the voice assistant in the kitchen, the TV, the vacuum cleaner, the thermostat, glasses and watches.',
      body: [
        ['The AI we use without noticing', 'Even before chatbots, artificial intelligence reached our homes inside features we take for granted: the camera that improves a night shot, the keyboard that suggests a word, the filter that stops spam, the robot vacuum that recognises an obstacle. Now manufacturers are adding <strong>generative assistants</strong> to the same devices, able to summarise, translate, write and answer by voice far more naturally.'],
        ['On the device or in the cloud?', 'This is the most useful distinction. A feature that runs <strong>on the device</strong> processes data locally: it is faster and more private, but needs recent chips. A feature that goes through the <strong>cloud</strong> is more powerful, but sends data to the maker\'s servers and often depends on a subscription. That is why many new features arrive only on the latest models, and some are available in certain countries before others.'],
        ['A home that talks to itself', 'Lights, locks, thermostats and plugs from different brands long struggled to talk to each other. The Matter standard, backed by the main manufacturers, was created so that devices from different ecosystems work together. With the new generation of assistants, the stated aim is to move from single commands ("turn on the light") to broader requests ("get the house ready for the night"). How much of this truly works, and at what cost to privacy, is worth checking story by story.']
      ],
      watch: ['AI features on iPhone, Android and other smartphones, and which models get them', 'voice assistants: Alexa, Siri, Gemini and their updates', 'appliances, TVs, glasses and wearables with AI', 'privacy and the data collected at home'],
      faq: [
        ['What does on-device AI mean?', 'It means the processing happens directly in the phone, computer or appliance, without sending data to a server. It is faster and better for privacy, but needs recent processors and smaller models than those used in the cloud.'],
        ['Do I need a new smartphone to use artificial intelligence?', 'Not for apps such as ChatGPT, Claude or Gemini: they work on almost any phone because they run in the cloud. AI features built into the system, however, are often reserved for the latest models, because they need suitable chips and memory.'],
        ['Are voice assistants always listening?', 'The devices wait for the wake word and, according to their makers, send audio to the servers only after recognising it. The settings let you review and delete recordings and switch off the microphone: it is worth checking them, also because the terms change with updates.'],
        ['What is Matter?', 'It is an open smart-home standard, backed by the biggest manufacturers, that lets devices from different brands work together and be controlled from the app or assistant you prefer.'],
        ['Is an appliance "with AI" worth buying?', 'It depends on what it actually does. The AI label is used both for useful functions, such as recognising the load or obstacles, and for plain marketing. Before buying, find out whether the feature works without a connection, whether it needs an account and for how many years the product will receive updates.']
      ]
    },
    medicina: {
      slug: 'ai-medicine-health', name: 'Medicine and health', short: 'AI in medicine and health',
      title: 'AI in medicine and health: discoveries, diagnosis and new drugs',
      desc: 'Artificial intelligence in medicine: diagnosis, imaging, new drugs, protein research and rules. News updated every hour with the source, videos and timeline.',
      lede: 'Earlier diagnoses, scans read with the help of an algorithm, molecules designed on a computer: medicine is one of the fields where artificial intelligence promises most, and where it matters most to tell proven results from announcements.',
      body: [
        ['Where AI is already on the ward', 'The most established uses involve <strong>images</strong>: X-rays, CT and MRI scans, mammograms, photographs of the skin and the retina. Here AI systems work as a second pair of eyes, flagging suspicious cases for the doctor or ranking exams by urgency. Health authorities, starting with the one in the United States, have cleared hundreds of devices of this kind over the years. The decision, however, stays with the doctor.'],
        ['Research: proteins and drugs', 'The best-known result is AlphaFold, the Google DeepMind system that predicts the shape of proteins from their sequence: a problem that had been open for half a century, and work honoured with the 2024 Nobel Prize in Chemistry. Knowing a protein\'s shape helps to understand diseases and to design molecules that bind to it. This is where many companies are using AI to shorten the early stages of drug discovery, although trials in people still take a long time.'],
        ['How to read medical news', 'There is a long way between a headline and a cure. A study on cells or animals is not a therapy; an algorithm tested in one hospital may perform worse elsewhere; a company press release is not a scientific paper. That is why FAIND always names the outlet and links to the original article. <strong>These pages inform; they do not replace a doctor\'s advice.</strong>']
      ],
      watch: ['diagnosis and the reading of medical images', 'drug discovery, proteins and genetics', 'chatbots and assistants for doctors and patients', 'rules, approvals and the protection of health data'],
      faq: [
        ['How is artificial intelligence used in medicine?', 'Mainly to analyse medical images, spot early signs of disease, rank exams by urgency, lighten doctors\' paperwork and speed up the search for new drugs. In almost every case it is a support tool, not a replacement for the doctor.'],
        ['Can AI make a diagnosis instead of a doctor?', 'No. Approved systems flag and suggest, but the diagnosis and the responsibility remain with a professional. Chatbots can help you understand a report or prepare for an appointment, but they can be wrong and do not know your medical history.'],
        ['What is AlphaFold?', 'It is an artificial intelligence system developed by Google DeepMind that predicts the three-dimensional structure of proteins. Its predictions are available to researchers worldwide and the work was honoured with the 2024 Nobel Prize in Chemistry.'],
        ['Can I ask a chatbot for medical advice?', 'A chatbot can explain terms, help you prepare questions for the doctor and give general information, but it does not examine you, does not know the full picture and can give wrong answers in a confident tone. For symptoms, treatments and medicines, see a doctor; in an emergency, call the emergency services.'],
        ['Is health data safe with AI?', 'Health data is among the most protected under European privacy law, and many medical AI systems fall into the high-risk category of the EU regulation on artificial intelligence. Before uploading reports or scans to a service, read how they are stored and used.']
      ]
    },
    lavoro: {
      slug: 'ai-jobs-work', name: 'AI and work', short: 'AI and work',
      title: 'AI and work: how jobs, skills and companies are changing',
      desc: 'Artificial intelligence and work: changing professions, new skills, layoffs and hiring, rules. News with the source, videos, timeline and the most in-demand AI roles.',
      lede: 'Will artificial intelligence take our jobs? Many people are asking. The honest answer is that it depends on the job, the tasks and the timing: here FAIND lines up the facts, day by day, with the source.',
      body: [
        ['Tasks, not jobs', 'Hardly any job consists of a single activity. Generative AI can already write drafts, summarise documents, translate, produce code, analyse data and answer recurring questions. Within each profession, then, some <strong>tasks</strong> are automated and others gain value: judgement, relationships with people, responsibility for a decision. That is why researchers speak more often of jobs that change than of jobs that vanish overnight.'],
        ['Who is most exposed', 'Earlier waves of automation mostly affected repetitive manual work. This one also reaches <strong>office and knowledge work</strong>: administration, customer service, translation, programming, graphic design, marketing, legal professions. Estimates of how many jobs will be lost or created differ widely from one study to the next, and overly neat numbers deserve suspicion. Real data is more useful: job ads, layoffs attributed to AI, union agreements, measured productivity.'],
        ['The skills that matter', 'Not everyone needs to become a programmer. What matters is using the tools well in your own field: asking the right question, checking the result, knowing where AI gets things wrong and which data must not be shared. Alongside this, jobs in AI itself are growing. Every day FAIND publishes the <a href="{home}#job">ranking of the most in-demand roles</a> in job ads, with links to apply.']
      ],
      watch: ['layoffs, hiring and reorganisations linked to AI', 'studies on productivity, wages and employment', 'training, skills and new professions', 'rules: AI in recruitment, monitoring of workers, union agreements'],
      faq: [
        ['Will artificial intelligence take our jobs?', 'It automates individual tasks more than whole jobs. Some activities, especially repetitive office work, are increasingly done by software; others are created or become more important. The effect depends on the sector and on how quickly companies adopt these tools.'],
        ['Which jobs are most at risk from AI?', 'Those dominated by repetitive tasks based on text and data: data entry, first-level customer service, standard translation, part of administrative work and basic programming. Jobs that require physical presence, fine manual skill, relationships and direct responsibility are less exposed.'],
        ['What are the most in-demand jobs in artificial intelligence?', 'Machine learning engineer, AI engineer, data scientist, data engineer and data analyst are among the roles that appear most often in job ads. Every six hours FAIND updates a ranking based on public listings from the last 30 days.'],
        ['What skills do you need to work with AI?', 'For most people: writing clear requests, checking the answers, knowing the limits of the tools and protecting confidential data. For technical roles: programming, statistics, data management and knowledge of machine learning models.'],
        ['Can a company use AI to select or assess employees?', 'In the European Union, AI systems used to hire, assess or manage workers are classed as high-risk by the regulation on artificial intelligence and are subject to specific transparency and human-oversight obligations, in addition to existing privacy and labour law.']
      ]
    },
    clima: {
      slug: 'ai-climate-environment', name: 'Climate and environment', short: 'AI, climate and environment',
      title: 'AI, climate and environment: energy, consumption and solutions',
      desc: 'How much artificial intelligence consumes and how it can help the climate: data centres, energy, water, weather forecasts, renewables. News with the source, videos and timeline.',
      lede: 'Artificial intelligence has two faces when it comes to the environment: it uses energy and water, and at the same time it is a tool for forecasting the weather, running power grids and studying the climate. On this page FAIND follows both.',
      body: [
        ['How much AI consumes', 'Training and running models requires large <strong>data centres</strong>, buildings full of computers that draw electricity and need cooling, often with water. International energy agencies expect data-centre electricity use to grow strongly in the coming years, and big technology companies have acknowledged that AI makes it harder to meet their own emissions targets. How much a single request to a chatbot weighs depends on the model and on how it is measured: the figures in circulation should be read with the source next to them.'],
        ['How AI can help', 'On the other side, AI models are improving <strong>weather forecasts</strong>, in some cases computing far faster than traditional methods. They are used to predict solar and wind output, balance power grids, cut waste in buildings and factories, spot wildfires and methane leaks from satellites, and search for new materials for batteries and panels.'],
        ['The final bill', 'Whether the balance turns out positive or negative is not settled: it depends on how much clean energy powers the data centres, on how efficient chips and models become, and on what we choose to do with all this computing power. It is also a local issue, because new sites ask the communities that host them for electricity, water and land, and protests and legal challenges are not lacking. Here we also follow climate and environment news in general, when it helps to understand the context.']
      ],
      watch: ['electricity and water use of data centres', 'energy for AI: renewables, nuclear, grids', 'AI for weather, climate, agriculture and natural disasters', 'local protests, rules and companies\' emissions pledges'],
      faq: [
        ['How much energy does artificial intelligence use?', 'It depends on the model and on the use. Most of the consumption happens in data centres, both to train models and to answer everyday requests. International estimates point to strong growth in data-centre electricity demand in the coming years, driven in part by AI.'],
        ['Why do data centres use water?', 'Because computers produce heat and many sites cool them with systems that use water, either directly or through the generation of the electricity they consume. The amount varies widely with the cooling technology and the local climate.'],
        ['Can AI help fight climate change?', 'It can contribute: it improves weather forecasts, helps run power grids with a lot of renewables, cuts energy waste, speeds up research into new materials and makes it possible to monitor forests, ice and emissions from satellites. It does not replace political and economic choices on cutting emissions.'],
        ['Does using a chatbot pollute?', 'Each request uses a small amount of energy, which becomes significant when multiplied by billions of uses. The real impact depends on the model, the efficiency of the data centre and the energy source that powers it.'],
        ['How are AI data centres powered?', 'With electricity from the grid, which has a different mix of sources in each country. Big companies are signing contracts for solar, wind and nuclear power and in some cases building dedicated plants; where that is not enough, gas is used as well.']
      ]
    }
  },

  fr: {
    robot: {
      slug: 'robots-humanoides', name: 'Robotique et humanoïdes', short: 'les robots et les humanoïdes',
      title: 'Robots et humanoïdes : actualités, vidéos et état des lieux',
      desc: 'Robots humanoïdes, voitures autonomes, drones et robots dans l\'espace : les actualités mises à jour chaque heure avec la source, les vidéos et la chronologie de FAIND.',
      lede: 'Des robots humanoïdes qui apprennent à se déplacer dans les entrepôts aux voitures sans conducteur, des drones aux rovers dans l\'espace : FAIND rassemble ici, heure par heure, ce qui se passe là où l\'intelligence artificielle rencontre le monde physique.',
      body: [
        ['Pourquoi on en parle tant aujourd\'hui', 'Pendant des décennies, les robots sont restés enfermés dans les usines, à répéter le même geste derrière une cage de sécurité. La nouveauté, c\'est que les modèles d\'intelligence artificielle, ceux-là mêmes qui ont appris à comprendre textes et images, servent désormais à faire <strong>voir, comprendre et agir</strong> une machine dans des lieux qui n\'ont pas été préparés pour elle. C\'est pourquoi des entreprises comme Tesla, Figure, Unitree et Boston Dynamics montrent des humanoïdes qui marchent, saisissent des objets et accomplissent des tâches simples.'],
        ['Humanoïdes : entre démonstrations et réalité', 'Une vidéo réussie n\'est pas encore un produit. Les questions à se poser devant chaque annonce sont toujours les mêmes : le robot agit-il seul ou est-il piloté à distance ? Combien de temps tient la batterie ? Combien coûte-t-il, et qui l\'utilise vraiment hors du laboratoire ? Pour l\'instant, les premiers usages concrets se trouvent dans la logistique et sur les lignes de production, où les tâches sont répétitives et l\'environnement maîtrisé. La maison, pleine d\'imprévus, reste l\'objectif le plus difficile.'],
        ['Pas seulement des humanoïdes', 'La robotique qui fonctionne déjà a souvent des formes moins spectaculaires : les robotaxis qui transportent des passagers sans conducteur dans certaines villes, les drones de livraison et d\'inspection, les robots chirurgicaux guidés par le médecin, les bras dans les entrepôts, les rovers et les satellites qui décident seuls parce qu\'ils sont trop loin pour être télécommandés. Tout suivre ensemble aide à voir où la technologie est mûre et où elle n\'est encore qu\'une promesse.']
      ],
      watch: ['les nouveaux modèles d\'humanoïdes et leurs premiers usages réels en usine et en entrepôt', 'la conduite autonome : robotaxis, autorisations, accidents et règles', 'drones, robots domestiques et d\'assistance', 'la robotique dans l\'espace, en mer et dans l\'agriculture'],
      faq: [
        ['Qu\'est-ce qu\'un robot humanoïde ?', 'C\'est un robot dont la forme rappelle celle d\'un être humain, en général avec deux jambes, deux bras et des mains capables de saisir des objets. L\'idée est qu\'il puisse se déplacer et travailler dans des lieux conçus pour les personnes, sans avoir à les modifier.'],
        ['Les robots humanoïdes sont-ils déjà en vente ?', 'Certains modèles peuvent être achetés par des entreprises et des centres de recherche, et quelques fabricants ont annoncé des versions grand public. Pour l\'essentiel, il s\'agit encore de projets pilotes dans des usines et des entrepôts : prix, autonomie et fiabilité varient beaucoup d\'une annonce à l\'autre, d\'où l\'intérêt de suivre l\'actualité avec la source.'],
        ['Quelle différence entre un robot et l\'intelligence artificielle ?', 'L\'intelligence artificielle est le logiciel qui reconnaît, prévoit et décide ; le robot est la machine qui agit dans le monde physique. Un robot peut fonctionner sans IA en répétant des mouvements programmés ; l\'IA lui permet de s\'adapter à des situations imprévues.'],
        ['Les voitures autonomes existent-elles vraiment ?', 'Oui : dans certaines villes du monde, des services de robotaxis circulent sans conducteur à bord, dans des zones et des conditions définies. La conduite entièrement autonome partout et par tous les temps n\'est pas encore une réalité.'],
        ['Les robots vont-ils prendre le travail des gens ?', 'Ils automatisent surtout des tâches répétitives, pénibles ou dangereuses, ce qui transforme les métiers plus qu\'il ne les supprime tous d\'un coup. Les effets dépendent du secteur et du rythme d\'adoption : FAIND suit aussi ce sujet sur sa page consacrée à l\'IA et au travail.']
      ]
    },
    domus: {
      slug: 'ia-a-la-maison', name: 'Domus : l\'IA à la maison', short: 'l\'IA à la maison',
      title: 'L\'IA à la maison : smartphones, maison connectée et électroménager',
      desc: 'L\'intelligence artificielle dans les objets du quotidien : smartphones, assistants vocaux, maison connectée, téléviseurs et électroménager. Actualités avec la source, vidéos et chronologie.',
      lede: 'Domus, c\'est la maison en latin. Sur cette page, FAIND suit l\'intelligence artificielle qui entre dans les objets de tous les jours : le téléphone dans la poche, l\'assistant vocal dans la cuisine, le téléviseur, l\'aspirateur, le thermostat, les lunettes et les montres.',
      body: [
        ['L\'IA que nous utilisons sans nous en rendre compte', 'Avant même les chatbots, l\'intelligence artificielle est entrée chez nous dans des fonctions qui semblent aller de soi : l\'appareil photo qui améliore un cliché de nuit, le clavier qui suggère un mot, le filtre qui bloque le spam, l\'aspirateur robot qui reconnaît un obstacle. Aujourd\'hui, les fabricants ajoutent aux mêmes appareils des <strong>assistants génératifs</strong>, capables de résumer, traduire, écrire et répondre à la voix de façon bien plus naturelle.'],
        ['Sur l\'appareil ou dans le cloud ?', 'C\'est la distinction la plus utile pour s\'y retrouver. Une fonction qui tourne <strong>sur l\'appareil</strong> traite les données localement : elle est plus rapide et plus confidentielle, mais exige des puces récentes. Une fonction qui passe par le <strong>cloud</strong> est plus puissante, mais envoie des données aux serveurs du fabricant et dépend souvent d\'un abonnement. C\'est pourquoi de nombreuses nouveautés n\'arrivent que sur les modèles les plus récents, et parfois dans certains pays avant d\'autres.'],
        ['Une maison qui se parle', 'Lampes, serrures, thermostats et prises de marques différentes ont longtemps eu du mal à dialoguer. Le standard Matter, soutenu par les principaux fabricants, a été créé pour faire fonctionner ensemble des appareils d\'écosystèmes différents. Avec les assistants de nouvelle génération, l\'objectif affiché est de passer des commandes isolées (« allume la lumière ») à des demandes plus larges (« prépare la maison pour la nuit »). Ce qui fonctionne vraiment, et à quel prix pour la vie privée, mérite d\'être vérifié actualité par actualité.']
      ],
      watch: ['les fonctions IA de l\'iPhone, d\'Android et des autres smartphones, et les modèles concernés', 'les assistants vocaux : Alexa, Siri, Gemini et leurs mises à jour', 'électroménager, téléviseurs, lunettes et objets connectés dotés d\'IA', 'vie privée et données collectées à la maison'],
      faq: [
        ['Que signifie l\'IA sur l\'appareil ?', 'Cela signifie que le traitement se fait directement dans le téléphone, l\'ordinateur ou l\'appareil ménager, sans envoyer de données à un serveur. C\'est plus rapide et plus respectueux de la vie privée, mais cela demande des processeurs récents et des modèles plus petits que ceux utilisés dans le cloud.'],
        ['Faut-il un smartphone neuf pour utiliser l\'intelligence artificielle ?', 'Pas pour des applications comme ChatGPT, Claude ou Gemini : elles fonctionnent sur presque tous les téléphones, car elles tournent dans le cloud. Les fonctions IA intégrées au système sont en revanche souvent réservées aux modèles récents, qui disposent des puces et de la mémoire nécessaires.'],
        ['Les assistants vocaux écoutent-ils en permanence ?', 'Les appareils attendent le mot d\'activation et, selon leurs fabricants, n\'envoient l\'audio aux serveurs qu\'après l\'avoir reconnu. Les réglages permettent de consulter et d\'effacer les enregistrements et de couper le micro : mieux vaut les vérifier, d\'autant que les conditions changent avec les mises à jour.'],
        ['Qu\'est-ce que Matter ?', 'C\'est un standard ouvert pour la maison connectée, soutenu par les plus grands fabricants, qui permet à des appareils de marques différentes de fonctionner ensemble et d\'être pilotés depuis l\'application ou l\'assistant de son choix.'],
        ['Faut-il acheter un appareil « avec IA » ?', 'Tout dépend de ce qu\'il fait réellement. L\'étiquette IA sert aussi bien pour des fonctions utiles, comme la reconnaissance de la charge ou des obstacles, que pour du simple marketing. Avant d\'acheter, vérifiez si la fonction marche sans connexion, si elle exige un compte et pendant combien d\'années le produit recevra des mises à jour.']
      ]
    },
    medicina: {
      slug: 'ia-medecine-sante', name: 'Médecine et santé', short: 'l\'IA en médecine et en santé',
      title: 'L\'IA en médecine et en santé : découvertes, diagnostic et nouveaux médicaments',
      desc: 'L\'intelligence artificielle en médecine : diagnostic, imagerie, nouveaux médicaments, recherche sur les protéines et règles. Actualités mises à jour chaque heure avec la source, vidéos et chronologie.',
      lede: 'Des diagnostics plus précoces, des images lues avec l\'aide d\'un algorithme, des molécules conçues par ordinateur : la médecine est l\'un des domaines où l\'intelligence artificielle promet le plus, et où il importe le plus de distinguer les résultats prouvés des annonces.',
      body: [
        ['Là où l\'IA est déjà à l\'hôpital', 'Les usages les plus établis concernent les <strong>images</strong> : radiographies, scanners, IRM, mammographies, photographies de la peau et de la rétine. Les systèmes d\'IA y jouent le rôle d\'une seconde paire d\'yeux, qui signale au médecin les cas suspects ou classe les examens par urgence. Les autorités sanitaires, à commencer par celle des États-Unis, ont autorisé au fil des ans des centaines de dispositifs de ce type. La décision, elle, reste au médecin.'],
        ['La recherche : protéines et médicaments', 'Le résultat le plus célèbre est AlphaFold, le système de Google DeepMind qui prédit la forme des protéines à partir de leur séquence : un problème resté ouvert pendant un demi-siècle, et un travail récompensé par le prix Nobel de chimie 2024. Connaître la forme d\'une protéine aide à comprendre les maladies et à concevoir des molécules qui s\'y lient. C\'est là que de nombreuses entreprises utilisent l\'IA pour raccourcir les premières étapes de la découverte d\'un médicament, même si les essais sur les personnes restent longs.'],
        ['Comment lire l\'actualité médicale', 'Entre un titre et un traitement, le chemin est long. Une étude sur des cellules ou des animaux n\'est pas une thérapie ; un algorithme testé dans un seul hôpital peut être moins bon ailleurs ; un communiqué d\'entreprise n\'est pas une publication scientifique. C\'est pourquoi FAIND indique toujours le média et renvoie à l\'article original. <strong>Ces pages informent, elles ne remplacent pas l\'avis d\'un médecin.</strong>']
      ],
      watch: ['le diagnostic et la lecture des images médicales', 'la découverte de médicaments, les protéines et la génétique', 'les chatbots et assistants pour médecins et patients', 'les règles, les autorisations et la protection des données de santé'],
      faq: [
        ['Comment l\'intelligence artificielle est-elle utilisée en médecine ?', 'Surtout pour analyser des images médicales, repérer des signes précoces de maladie, classer les examens par urgence, alléger le travail administratif des médecins et accélérer la recherche de nouveaux médicaments. Dans presque tous les cas, c\'est un outil d\'aide, pas un remplaçant du médecin.'],
        ['L\'IA peut-elle poser un diagnostic à la place du médecin ?', 'Non. Les systèmes autorisés signalent et suggèrent, mais le diagnostic et la responsabilité restent à un professionnel. Les chatbots peuvent aider à comprendre un compte rendu ou à préparer une consultation, mais ils peuvent se tromper et ne connaissent pas le dossier médical de la personne.'],
        ['Qu\'est-ce qu\'AlphaFold ?', 'C\'est un système d\'intelligence artificielle développé par Google DeepMind qui prédit la structure tridimensionnelle des protéines. Ses prédictions sont à la disposition des chercheurs du monde entier et ce travail a été récompensé par le prix Nobel de chimie 2024.'],
        ['Puis-je demander un avis médical à un chatbot ?', 'Un chatbot peut expliquer des termes, aider à préparer des questions pour le médecin et donner des informations générales, mais il n\'examine pas, ne connaît pas l\'ensemble du tableau et peut donner des réponses fausses sur un ton assuré. Pour des symptômes, des traitements ou des médicaments, consultez un médecin ; en cas d\'urgence, appelez les secours.'],
        ['Les données de santé sont-elles en sécurité avec l\'IA ?', 'Les données de santé comptent parmi les plus protégées par le droit européen, et de nombreux systèmes d\'IA médicale relèvent de la catégorie à haut risque du règlement européen sur l\'intelligence artificielle. Avant de téléverser des comptes rendus ou des examens sur un service, lisez comment ils sont conservés et utilisés.']
      ]
    },
    lavoro: {
      slug: 'ia-travail', name: 'IA et travail', short: 'l\'IA et le travail',
      title: 'IA et travail : comment changent les métiers, les compétences et les entreprises',
      desc: 'Intelligence artificielle et travail : métiers qui changent, nouvelles compétences, licenciements et embauches, règles. Actualités avec la source, vidéos, chronologie et métiers de l\'IA les plus recherchés.',
      lede: 'L\'intelligence artificielle va-t-elle nous prendre notre travail ? Beaucoup se posent la question. La réponse honnête est que cela dépend du métier, des tâches et du calendrier : FAIND aligne ici les faits, jour après jour, avec la source.',
      body: [
        ['Des tâches, pas des métiers', 'Presque aucun métier ne se résume à une seule activité. L\'IA générative sait déjà rédiger des brouillons, résumer des documents, traduire, produire du code, analyser des données, répondre aux questions récurrentes. Au sein de chaque profession, certaines <strong>tâches</strong> s\'automatisent donc tandis que d\'autres prennent de la valeur : le jugement, la relation avec les personnes, la responsabilité d\'une décision. C\'est pourquoi les chercheurs parlent plus souvent de métiers qui se transforment que de métiers qui disparaissent du jour au lendemain.'],
        ['Qui est le plus exposé', 'Les vagues d\'automatisation précédentes ont surtout touché le travail manuel répétitif. Celle-ci concerne aussi le <strong>travail de bureau et intellectuel</strong> : administration, service client, traduction, programmation, graphisme, marketing, professions juridiques. Les estimations du nombre d\'emplois perdus ou créés varient beaucoup d\'une étude à l\'autre, et les chiffres trop nets appellent la méfiance. Les données réelles sont plus utiles : offres d\'emploi, licenciements attribués à l\'IA, accords syndicaux, productivité mesurée.'],
        ['Les compétences utiles', 'Tout le monde n\'a pas besoin de devenir programmeur. Il faut savoir bien utiliser les outils dans son domaine : formuler la bonne demande, vérifier le résultat, comprendre où l\'IA se trompe, savoir quelles données ne doivent pas être partagées. Parallèlement, les métiers de l\'IA proprement dite progressent. FAIND publie chaque jour le <a href="{home}#job">classement des métiers les plus recherchés</a> dans les offres, avec les liens pour postuler.']
      ],
      watch: ['licenciements, embauches et réorganisations liés à l\'IA', 'études sur la productivité, les salaires et l\'emploi', 'formation, compétences et nouveaux métiers', 'règles : IA dans le recrutement, surveillance des salariés, accords syndicaux'],
      faq: [
        ['L\'intelligence artificielle va-t-elle nous prendre notre travail ?', 'Elle automatise des tâches plus que des métiers entiers. Certaines activités, surtout répétitives et de bureau, sont de plus en plus confiées au logiciel ; d\'autres apparaissent ou gagnent en importance. L\'effet dépend du secteur et de la vitesse à laquelle les entreprises adoptent ces outils.'],
        ['Quels métiers sont les plus menacés par l\'IA ?', 'Ceux où dominent des tâches répétitives fondées sur le texte et les données : saisie, service client de premier niveau, traduction standard, une partie du travail administratif et de la programmation de base. Les métiers qui exigent une présence physique, une habileté manuelle fine, de la relation et une responsabilité directe sont moins exposés.'],
        ['Quels sont les métiers les plus recherchés dans l\'intelligence artificielle ?', 'Machine learning engineer, AI engineer, data scientist, data engineer et data analyst figurent parmi les postes qui reviennent le plus dans les offres. FAIND met à jour toutes les six heures un classement fondé sur les annonces publiques des 30 derniers jours.'],
        ['Quelles compétences faut-il pour travailler avec l\'IA ?', 'Pour la plupart des gens : savoir formuler des demandes claires, vérifier les réponses, connaître les limites des outils et protéger les données confidentielles. Pour les postes techniques : programmation, statistiques, gestion des données et connaissance des modèles de machine learning.'],
        ['Une entreprise peut-elle utiliser l\'IA pour sélectionner ou évaluer ses salariés ?', 'Dans l\'Union européenne, les systèmes d\'IA utilisés pour recruter, évaluer ou gérer les travailleurs sont classés à haut risque par le règlement sur l\'intelligence artificielle et soumis à des obligations spécifiques de transparence et de contrôle humain, en plus du droit du travail et de la protection des données déjà en vigueur.']
      ]
    },
    clima: {
      slug: 'ia-climat-environnement', name: 'Climat et environnement', short: 'l\'IA, le climat et l\'environnement',
      title: 'IA, climat et environnement : énergie, consommation et solutions',
      desc: 'Combien consomme l\'intelligence artificielle et comment elle peut aider le climat : centres de données, énergie, eau, prévisions météo, renouvelables. Actualités avec la source, vidéos et chronologie.',
      lede: 'L\'intelligence artificielle a deux visages lorsqu\'on parle d\'environnement : elle consomme de l\'énergie et de l\'eau, et c\'est en même temps un outil pour prévoir la météo, gérer les réseaux électriques et étudier le climat. Sur cette page, FAIND suit les deux.',
      body: [
        ['Ce que consomme l\'IA', 'Entraîner et faire fonctionner les modèles exige de grands <strong>centres de données</strong>, des bâtiments remplis d\'ordinateurs qui absorbent de l\'électricité et qu\'il faut refroidir, souvent avec de l\'eau. Les agences internationales de l\'énergie prévoient une forte hausse de la consommation électrique des centres de données dans les prochaines années, et les grandes entreprises technologiques ont reconnu que l\'IA rend plus difficile le respect de leurs propres objectifs d\'émissions. Le poids d\'une seule requête à un chatbot dépend du modèle et de la méthode de mesure : les chiffres qui circulent se lisent avec la source à côté.'],
        ['Comment l\'IA peut aider', 'À l\'inverse, les modèles d\'intelligence artificielle améliorent les <strong>prévisions météorologiques</strong>, parfois avec une rapidité de calcul très supérieure à celle des méthodes traditionnelles. Ils servent à prévoir la production solaire et éolienne, équilibrer les réseaux électriques, réduire le gaspillage dans les bâtiments et les usines, repérer incendies et fuites de méthane depuis les satellites, chercher de nouveaux matériaux pour les batteries et les panneaux.'],
        ['L\'addition finale', 'Le bilan sera-t-il positif ou négatif ? Rien n\'est joué : tout dépend de la part d\'énergie propre qui alimentera les centres de données, des gains d\'efficacité des puces et des modèles, et de ce que l\'on choisira de faire de cette puissance de calcul. C\'est aussi une question de territoires, car les nouveaux sites demandent de l\'électricité, de l\'eau et des terrains aux communautés qui les accueillent, et les protestations et recours ne manquent pas. Nous suivons aussi ici l\'actualité du climat et de l\'environnement en général, lorsqu\'elle aide à comprendre le contexte.']
      ],
      watch: ['la consommation d\'électricité et d\'eau des centres de données', 'l\'énergie pour l\'IA : renouvelables, nucléaire, réseaux', 'l\'IA pour la météo, le climat, l\'agriculture et les catastrophes naturelles', 'protestations locales, règles et engagements des entreprises sur les émissions'],
      faq: [
        ['Combien d\'énergie consomme l\'intelligence artificielle ?', 'Cela dépend du modèle et de l\'usage. L\'essentiel de la consommation a lieu dans les centres de données, pour entraîner les modèles comme pour répondre aux requêtes quotidiennes. Les estimations internationales annoncent une forte hausse de la demande électrique des centres de données dans les prochaines années, tirée en partie par l\'IA.'],
        ['Pourquoi les centres de données consomment-ils de l\'eau ?', 'Parce que les ordinateurs produisent de la chaleur et que de nombreux sites les refroidissent avec des systèmes utilisant de l\'eau, directement ou à travers la production de l\'électricité qu\'ils consomment. La quantité varie beaucoup selon la technologie de refroidissement et le climat local.'],
        ['L\'IA peut-elle aider à lutter contre le changement climatique ?', 'Elle peut y contribuer : elle améliore les prévisions météo, aide à gérer des réseaux électriques riches en renouvelables, réduit le gaspillage d\'énergie, accélère la recherche sur de nouveaux matériaux et permet de surveiller forêts, glaces et émissions depuis les satellites. Elle ne remplace pas les choix politiques et économiques de réduction des émissions.'],
        ['Utiliser un chatbot pollue-t-il ?', 'Chaque requête consomme une petite quantité d\'énergie, qui devient significative une fois multipliée par des milliards d\'usages. L\'impact réel dépend du modèle, de l\'efficacité du centre de données et de la source d\'énergie qui l\'alimente.'],
        ['Comment les centres de données de l\'IA sont-ils alimentés ?', 'Par l\'électricité du réseau, dont le mix varie d\'un pays à l\'autre. Les grandes entreprises signent des contrats pour de l\'énergie solaire, éolienne et nucléaire et construisent parfois des installations dédiées ; lorsque cela ne suffit pas, le gaz est aussi utilisé.']
      ]
    }
  },

  de: {
    robot: {
      slug: 'humanoide-roboter', name: 'Robotik & Humanoide', short: 'Roboter und Humanoide',
      title: 'Roboter und Humanoide: Nachrichten, Videos und aktueller Stand',
      desc: 'Humanoide Roboter, selbstfahrende Autos, Drohnen und Roboter im All: stündlich aktualisierte Nachrichten mit Quelle, Videos und die FAIND-Chronik.',
      lede: 'Von humanoiden Robotern, die sich in Lagerhallen bewegen lernen, bis zu fahrerlosen Autos, von Drohnen bis zu Rovern im All: Hier sammelt FAIND Stunde für Stunde, was dort geschieht, wo künstliche Intelligenz auf die physische Welt trifft.',
      body: [
        ['Warum gerade jetzt so viel darüber gesprochen wird', 'Jahrzehntelang blieben Roboter in Fabriken und wiederholten hinter einem Schutzgitter dieselbe Bewegung. Neu ist, dass KI-Modelle, dieselben, die Texte und Bilder verstehen gelernt haben, nun auch dazu dienen, eine Maschine in Umgebungen <strong>sehen, verstehen und handeln</strong> zu lassen, die nicht eigens für sie vorbereitet wurden. Deshalb zeigen Unternehmen wie Tesla, Figure, Unitree und Boston Dynamics Humanoide, die gehen, Gegenstände greifen und einfache Aufgaben erledigen.'],
        ['Humanoide: zwischen Vorführung und Wirklichkeit', 'Ein gelungenes Video ist noch kein Produkt. Die Fragen zu jeder Ankündigung sind immer dieselben: Handelt der Roboter selbstständig oder wird er ferngesteuert? Wie lange hält der Akku? Was kostet er, und wer setzt ihn wirklich außerhalb des Labors ein? Vorerst liegen die ersten konkreten Einsätze in der Logistik und an Fertigungslinien, wo die Aufgaben sich wiederholen und die Umgebung kontrolliert ist. Das Zuhause voller Überraschungen bleibt das schwierigste Ziel.'],
        ['Nicht nur Humanoide', 'Die Robotik, die bereits funktioniert, sieht oft weniger spektakulär aus: Robotaxis, die in einigen Städten Fahrgäste ohne Fahrer befördern, Drohnen für Lieferungen und Inspektionen, vom Arzt gesteuerte Operationsroboter, Greifarme in Lagern, Rover und Satelliten, die selbst entscheiden, weil sie zu weit entfernt sind, um ferngesteuert zu werden. Alles zusammen zu verfolgen hilft zu erkennen, wo die Technik ausgereift ist und wo sie noch ein Versprechen bleibt.']
      ],
      watch: ['neue Humanoiden-Modelle und erste echte Einsätze in Fabrik und Lager', 'autonomes Fahren: Robotaxis, Zulassungen, Unfälle und Regeln', 'Drohnen, Haushalts- und Pflegeroboter', 'Robotik im All, auf See und in der Landwirtschaft'],
      faq: [
        ['Was ist ein humanoider Roboter?', 'Ein Roboter, dessen Gestalt der eines Menschen ähnelt, meist mit zwei Beinen, zwei Armen und Händen, die Gegenstände greifen können. Die Idee: Er soll sich in Umgebungen bewegen und arbeiten, die für Menschen gebaut sind, ohne dass man sie umbauen muss.'],
        ['Kann man humanoide Roboter schon kaufen?', 'Einige Modelle sind für Unternehmen und Forschungseinrichtungen erhältlich, und einzelne Hersteller haben Versionen für Privatkunden angekündigt. Überwiegend handelt es sich aber noch um Pilotprojekte in Fabriken und Lagern: Preise, Akkulaufzeit und Zuverlässigkeit unterscheiden sich von Ankündigung zu Ankündigung stark, deshalb lohnt es sich, die Nachrichten mit Quelle zu verfolgen.'],
        ['Was ist der Unterschied zwischen einem Roboter und künstlicher Intelligenz?', 'Künstliche Intelligenz ist die Software, die erkennt, vorhersagt und entscheidet; der Roboter ist die Maschine, die in der physischen Welt handelt. Ein Roboter kann auch ohne KI arbeiten und programmierte Bewegungen ausführen; KI ermöglicht ihm, sich an unvorhergesehene Situationen anzupassen.'],
        ['Gibt es selbstfahrende Autos wirklich?', 'Ja: In einigen Städten der Welt fahren Robotaxi-Dienste ohne Fahrer an Bord, innerhalb festgelegter Gebiete und Bedingungen. Vollständig autonomes Fahren überall und bei jedem Wetter ist dagegen noch nicht Realität.'],
        ['Nehmen Roboter den Menschen die Arbeit weg?', 'Sie automatisieren vor allem eintönige, anstrengende oder gefährliche Tätigkeiten, was Berufe eher verändert, als sie alle auf einmal abzuschaffen. Die Folgen hängen von der Branche und vom Tempo der Einführung ab: FAIND verfolgt das Thema auch auf der Seite zu KI und Arbeit.']
      ]
    },
    domus: {
      slug: 'ki-zuhause', name: 'Domus: KI zu Hause', short: 'KI zu Hause',
      title: 'KI zu Hause: Smartphones, Smart Home und Haushaltsgeräte',
      desc: 'Künstliche Intelligenz in Alltagsgegenständen: Smartphones, Sprachassistenten, Smart Home, Fernseher und Haushaltsgeräte. Nachrichten mit Quelle, Videos und Chronik.',
      lede: 'Domus ist lateinisch für Haus. Auf dieser Seite verfolgt FAIND die künstliche Intelligenz, die in Alltagsgegenstände einzieht: das Telefon in der Tasche, der Sprachassistent in der Küche, der Fernseher, der Staubsauger, das Thermostat, Brillen und Uhren.',
      body: [
        ['Die KI, die wir unbemerkt nutzen', 'Schon vor den Chatbots kam künstliche Intelligenz in Funktionen ins Haus, die uns selbstverständlich erscheinen: die Kamera, die eine Nachtaufnahme verbessert, die Tastatur, die ein Wort vorschlägt, der Filter gegen Spam, der Saugroboter, der ein Hindernis erkennt. Heute ergänzen die Hersteller dieselben Geräte um <strong>generative Assistenten</strong>, die zusammenfassen, übersetzen, schreiben und deutlich natürlicher per Stimme antworten können.'],
        ['Auf dem Gerät oder in der Cloud?', 'Das ist die nützlichste Unterscheidung. Eine Funktion, die <strong>auf dem Gerät</strong> läuft, verarbeitet Daten lokal: Sie ist schneller und vertraulicher, braucht aber aktuelle Chips. Eine Funktion über die <strong>Cloud</strong> ist leistungsfähiger, sendet jedoch Daten an die Server des Herstellers und hängt oft von einem Abo ab. Deshalb kommen viele Neuerungen nur auf den neuesten Modellen an, und manche sind in einigen Ländern früher verfügbar als in anderen.'],
        ['Ein Zuhause, das miteinander spricht', 'Lampen, Schlösser, Thermostate und Steckdosen verschiedener Marken konnten lange kaum miteinander kommunizieren. Der von den wichtigsten Herstellern getragene Standard Matter soll Geräte unterschiedlicher Ökosysteme zusammenarbeiten lassen. Mit den Assistenten der neuen Generation lautet das erklärte Ziel, von einzelnen Befehlen („Licht an“) zu umfassenderen Wünschen („bereite das Haus für die Nacht vor“) zu gelangen. Wie viel davon wirklich funktioniert und zu welchem Preis für die Privatsphäre, sollte man Nachricht für Nachricht prüfen.']
      ],
      watch: ['KI-Funktionen von iPhone, Android und anderen Smartphones und auf welchen Modellen sie ankommen', 'Sprachassistenten: Alexa, Siri, Gemini und ihre Updates', 'Haushaltsgeräte, Fernseher, Brillen und Wearables mit KI', 'Privatsphäre und die zu Hause erhobenen Daten'],
      faq: [
        ['Was bedeutet KI auf dem Gerät?', 'Die Verarbeitung findet direkt im Telefon, Computer oder Haushaltsgerät statt, ohne Daten an einen Server zu senden. Das ist schneller und schützt die Privatsphäre besser, erfordert aber aktuelle Prozessoren und kleinere Modelle als in der Cloud.'],
        ['Brauche ich ein neues Smartphone, um künstliche Intelligenz zu nutzen?', 'Für Apps wie ChatGPT, Claude oder Gemini nicht: Sie funktionieren auf fast jedem Telefon, weil sie in der Cloud laufen. Ins System integrierte KI-Funktionen sind dagegen oft den neuesten Modellen vorbehalten, weil sie passende Chips und genügend Speicher brauchen.'],
        ['Hören Sprachassistenten ständig zu?', 'Die Geräte warten auf das Aktivierungswort und senden nach Angaben der Hersteller erst danach Audio an die Server. In den Einstellungen lassen sich Aufnahmen ansehen und löschen sowie das Mikrofon abschalten: Ein Blick lohnt sich, auch weil sich die Bedingungen mit Updates ändern.'],
        ['Was ist Matter?', 'Ein offener Smart-Home-Standard, den die größten Hersteller unterstützen. Er sorgt dafür, dass Geräte verschiedener Marken zusammenarbeiten und sich über die App oder den Assistenten der eigenen Wahl steuern lassen.'],
        ['Lohnt sich ein Haushaltsgerät „mit KI“?', 'Das hängt davon ab, was es wirklich kann. Das Etikett KI steht sowohl für nützliche Funktionen wie die Erkennung von Beladung oder Hindernissen als auch für reines Marketing. Vor dem Kauf sollte man klären, ob die Funktion ohne Internet läuft, ob sie ein Konto verlangt und wie viele Jahre das Produkt Updates erhält.']
      ]
    },
    medicina: {
      slug: 'ki-medizin-gesundheit', name: 'Medizin und Gesundheit', short: 'KI in Medizin und Gesundheit',
      title: 'KI in Medizin und Gesundheit: Entdeckungen, Diagnose und neue Medikamente',
      desc: 'Künstliche Intelligenz in der Medizin: Diagnose, Bildgebung, neue Medikamente, Proteinforschung und Regeln. Stündlich aktualisierte Nachrichten mit Quelle, Videos und Chronik.',
      lede: 'Frühere Diagnosen, Aufnahmen, die mithilfe eines Algorithmus gelesen werden, am Computer entworfene Moleküle: Die Medizin gehört zu den Feldern, in denen künstliche Intelligenz am meisten verspricht, und in denen es am wichtigsten ist, belegte Ergebnisse von Ankündigungen zu unterscheiden.',
      body: [
        ['Wo KI schon im Klinikalltag angekommen ist', 'Am etabliertesten ist der Einsatz bei <strong>Bildern</strong>: Röntgen, CT, MRT, Mammografien, Aufnahmen der Haut und der Netzhaut. Hier arbeiten KI-Systeme wie ein zweites Augenpaar, das dem Arzt verdächtige Fälle meldet oder Untersuchungen nach Dringlichkeit ordnet. Gesundheitsbehörden, allen voran die der USA, haben im Lauf der Jahre Hunderte solcher Produkte zugelassen. Die Entscheidung bleibt jedoch beim Arzt.'],
        ['Forschung: Proteine und Medikamente', 'Das bekannteste Ergebnis ist AlphaFold, das System von Google DeepMind, das die Form von Proteinen aus ihrer Sequenz vorhersagt: ein Problem, das ein halbes Jahrhundert offen war, und eine Arbeit, die 2024 mit dem Nobelpreis für Chemie gewürdigt wurde. Die Form eines Proteins zu kennen hilft, Krankheiten zu verstehen und Moleküle zu entwerfen, die daran binden. Hier setzen viele Unternehmen KI ein, um die frühen Phasen der Wirkstoffsuche zu verkürzen, auch wenn Studien am Menschen weiterhin lange dauern.'],
        ['Wie man Medizinnachrichten liest', 'Zwischen Schlagzeile und Therapie liegt ein weiter Weg. Eine Studie an Zellen oder Tieren ist keine Behandlung; ein Algorithmus, der in nur einem Krankenhaus getestet wurde, kann anderswo schlechter abschneiden; eine Pressemitteilung ist keine wissenschaftliche Veröffentlichung. Deshalb nennt FAIND stets das Medium und verweist auf den Originalartikel. <strong>Diese Seiten informieren, sie ersetzen keinen ärztlichen Rat.</strong>']
      ],
      watch: ['Diagnose und Auswertung medizinischer Bilder', 'Wirkstoffforschung, Proteine und Genetik', 'Chatbots und Assistenten für Ärzte und Patienten', 'Regeln, Zulassungen und der Schutz von Gesundheitsdaten'],
      faq: [
        ['Wie wird künstliche Intelligenz in der Medizin eingesetzt?', 'Vor allem, um medizinische Bilder auszuwerten, frühe Krankheitszeichen zu erkennen, Untersuchungen nach Dringlichkeit zu ordnen, Ärzte von Verwaltungsarbeit zu entlasten und die Suche nach neuen Medikamenten zu beschleunigen. In fast allen Fällen ist sie ein Hilfsmittel, kein Ersatz für den Arzt.'],
        ['Kann KI anstelle des Arztes eine Diagnose stellen?', 'Nein. Zugelassene Systeme melden und schlagen vor, doch Diagnose und Verantwortung bleiben bei einer Fachperson. Auch Chatbots können helfen, einen Befund zu verstehen oder einen Termin vorzubereiten, aber sie können sich irren und kennen die Krankengeschichte nicht.'],
        ['Was ist AlphaFold?', 'Ein von Google DeepMind entwickeltes KI-System, das die dreidimensionale Struktur von Proteinen vorhersagt. Seine Vorhersagen stehen Forschenden weltweit zur Verfügung; die Arbeit wurde 2024 mit dem Nobelpreis für Chemie gewürdigt.'],
        ['Kann ich einen Chatbot um medizinischen Rat fragen?', 'Ein Chatbot kann Begriffe erklären, bei Fragen an den Arzt helfen und allgemeine Informationen geben, aber er untersucht nicht, kennt nicht das Gesamtbild und kann in sicherem Ton falsche Antworten geben. Bei Symptomen, Therapien und Medikamenten gehört man zum Arzt; im Notfall ruft man den Rettungsdienst.'],
        ['Sind Gesundheitsdaten bei KI sicher?', 'Gesundheitsdaten gehören zu den am stärksten geschützten Daten im europäischen Recht, und viele medizinische KI-Systeme fallen in die Hochrisiko-Kategorie der EU-Verordnung über künstliche Intelligenz. Bevor man Befunde oder Aufnahmen bei einem Dienst hochlädt, sollte man nachlesen, wie sie gespeichert und genutzt werden.']
      ]
    },
    lavoro: {
      slug: 'ki-arbeit', name: 'KI und Arbeit', short: 'KI und Arbeit',
      title: 'KI und Arbeit: wie sich Berufe, Kompetenzen und Unternehmen verändern',
      desc: 'Künstliche Intelligenz und Arbeit: Berufe im Wandel, neue Kompetenzen, Entlassungen und Einstellungen, Regeln. Nachrichten mit Quelle, Videos, Chronik und die gefragtesten KI-Jobs.',
      lede: 'Nimmt uns die künstliche Intelligenz die Arbeit weg? Das fragen sich viele. Die ehrliche Antwort lautet: Es kommt auf den Beruf, die Aufgaben und den Zeitraum an. Hier reiht FAIND die Fakten auf, Tag für Tag, mit Quelle.',
      body: [
        ['Aufgaben, nicht Berufe', 'Kaum ein Beruf besteht aus nur einer Tätigkeit. Generative KI kann bereits Entwürfe schreiben, Dokumente zusammenfassen, übersetzen, Code erzeugen, Daten auswerten und wiederkehrende Fragen beantworten. Innerhalb jedes Berufs werden also manche <strong>Aufgaben</strong> automatisiert, während andere an Wert gewinnen: Urteilsvermögen, der Umgang mit Menschen, die Verantwortung für eine Entscheidung. Deshalb sprechen Forschende häufiger von Berufen, die sich wandeln, als von Berufen, die über Nacht verschwinden.'],
        ['Wer am stärksten betroffen ist', 'Frühere Automatisierungswellen trafen vor allem eintönige Handarbeit. Diese erreicht auch die <strong>Büro- und Wissensarbeit</strong>: Verwaltung, Kundenservice, Übersetzung, Programmierung, Grafik, Marketing, juristische Berufe. Schätzungen, wie viele Stellen verloren gehen oder entstehen, weichen von Studie zu Studie stark ab; allzu glatte Zahlen verdienen Misstrauen. Aufschlussreicher sind reale Daten: Stellenanzeigen, mit KI begründete Entlassungen, Tarifvereinbarungen, gemessene Produktivität.'],
        ['Die Kompetenzen, auf die es ankommt', 'Nicht jeder muss programmieren lernen. Wichtig ist, die Werkzeuge im eigenen Fach gut zu nutzen: die richtige Anfrage stellen, das Ergebnis prüfen, erkennen, wo KI danebenliegt, und wissen, welche Daten man nicht teilen darf. Daneben wachsen die eigentlichen KI-Berufe. FAIND veröffentlicht täglich die <a href="{home}#job">Rangliste der gefragtesten Rollen</a> in Stellenanzeigen, mit Links zur Bewerbung.']
      ],
      watch: ['Entlassungen, Einstellungen und Umstrukturierungen im Zusammenhang mit KI', 'Studien zu Produktivität, Löhnen und Beschäftigung', 'Weiterbildung, Kompetenzen und neue Berufe', 'Regeln: KI in der Personalauswahl, Überwachung von Beschäftigten, Tarifvereinbarungen'],
      faq: [
        ['Nimmt uns künstliche Intelligenz die Arbeit weg?', 'Sie automatisiert einzelne Aufgaben eher als ganze Berufe. Manche Tätigkeiten, vor allem wiederkehrende Büroarbeit, übernimmt zunehmend die Software; andere entstehen neu oder werden wichtiger. Die Wirkung hängt von der Branche ab und davon, wie schnell Unternehmen diese Werkzeuge einführen.'],
        ['Welche Berufe sind durch KI am stärksten gefährdet?', 'Jene, in denen wiederkehrende Aufgaben mit Text und Daten überwiegen: Dateneingabe, Kundenservice der ersten Ebene, Standardübersetzungen, ein Teil der Verwaltungsarbeit und der einfachen Programmierung. Weniger betroffen sind Berufe, die körperliche Anwesenheit, feines handwerkliches Geschick, Beziehungsarbeit und direkte Verantwortung erfordern.'],
        ['Welche Jobs sind in der künstlichen Intelligenz am gefragtesten?', 'Machine Learning Engineer, AI Engineer, Data Scientist, Data Engineer und Data Analyst gehören zu den Rollen, die in Stellenanzeigen am häufigsten vorkommen. FAIND aktualisiert alle sechs Stunden eine Rangliste auf Basis öffentlicher Anzeigen der letzten 30 Tage.'],
        ['Welche Kompetenzen braucht man für die Arbeit mit KI?', 'Für die meisten: klare Anfragen formulieren, Antworten überprüfen, die Grenzen der Werkzeuge kennen und vertrauliche Daten schützen. Für technische Rollen: Programmierung, Statistik, Datenmanagement und Kenntnisse über Modelle des maschinellen Lernens.'],
        ['Darf ein Unternehmen KI zur Auswahl oder Bewertung von Beschäftigten einsetzen?', 'In der Europäischen Union gelten KI-Systeme zur Einstellung, Bewertung oder Steuerung von Beschäftigten nach der KI-Verordnung als Hochrisiko-Systeme und unterliegen besonderen Pflichten zu Transparenz und menschlicher Aufsicht, zusätzlich zum bereits geltenden Datenschutz- und Arbeitsrecht.']
      ]
    },
    clima: {
      slug: 'ki-klima-umwelt', name: 'Klima und Umwelt', short: 'KI, Klima und Umwelt',
      title: 'KI, Klima und Umwelt: Energie, Verbrauch und Lösungen',
      desc: 'Wie viel künstliche Intelligenz verbraucht und wie sie dem Klima helfen kann: Rechenzentren, Energie, Wasser, Wettervorhersagen, Erneuerbare. Nachrichten mit Quelle, Videos und Chronik.',
      lede: 'Künstliche Intelligenz hat zwei Gesichter, wenn es um die Umwelt geht: Sie verbraucht Energie und Wasser, und zugleich ist sie ein Werkzeug, um das Wetter vorherzusagen, Stromnetze zu steuern und das Klima zu erforschen. Auf dieser Seite verfolgt FAIND beides.',
      body: [
        ['Wie viel KI verbraucht', 'Modelle zu trainieren und zu betreiben erfordert große <strong>Rechenzentren</strong>, Gebäude voller Computer, die Strom aufnehmen und gekühlt werden müssen, oft mit Wasser. Internationale Energieagenturen erwarten in den kommenden Jahren einen starken Anstieg des Stromverbrauchs von Rechenzentren, und große Technologiekonzerne haben eingeräumt, dass KI es schwerer macht, die eigenen Emissionsziele einzuhalten. Wie viel eine einzelne Anfrage an einen Chatbot ausmacht, hängt vom Modell und von der Messmethode ab: Die kursierenden Zahlen liest man am besten mit der Quelle daneben.'],
        ['Wie KI helfen kann', 'Auf der anderen Seite verbessern KI-Modelle die <strong>Wettervorhersage</strong>, teils mit weit höherer Rechengeschwindigkeit als herkömmliche Verfahren. Sie helfen, die Erzeugung von Sonnen- und Windstrom vorherzusagen, Stromnetze auszugleichen, Verschwendung in Gebäuden und Fabriken zu senken, Brände und Methanlecks per Satellit zu erkennen und neue Materialien für Batterien und Solarmodule zu finden.'],
        ['Die Schlussrechnung', 'Ob die Bilanz positiv oder negativ ausfällt, ist nicht entschieden: Es hängt davon ab, wie viel saubere Energie die Rechenzentren speist, wie effizient Chips und Modelle werden und was wir mit dieser Rechenleistung anfangen. Es ist auch ein Thema vor Ort, denn neue Anlagen verlangen von den Gemeinden, die sie beherbergen, Strom, Wasser und Fläche; Proteste und Klagen bleiben nicht aus. Wir verfolgen hier auch allgemeine Klima- und Umweltnachrichten, wenn sie helfen, den Zusammenhang zu verstehen.']
      ],
      watch: ['Strom- und Wasserverbrauch von Rechenzentren', 'Energie für KI: Erneuerbare, Kernkraft, Netze', 'KI für Wetter, Klima, Landwirtschaft und Naturkatastrophen', 'lokale Proteste, Regeln und Emissionszusagen der Unternehmen'],
      faq: [
        ['Wie viel Energie verbraucht künstliche Intelligenz?', 'Das hängt vom Modell und von der Nutzung ab. Der größte Teil des Verbrauchs entsteht in Rechenzentren, sowohl beim Training der Modelle als auch bei der Beantwortung alltäglicher Anfragen. Internationale Schätzungen gehen von einem starken Anstieg des Strombedarfs von Rechenzentren in den kommenden Jahren aus, auch getrieben durch KI.'],
        ['Warum verbrauchen Rechenzentren Wasser?', 'Weil Computer Wärme erzeugen und viele Anlagen sie mit Systemen kühlen, die Wasser nutzen, direkt oder über die Erzeugung des verbrauchten Stroms. Die Menge schwankt stark je nach Kühltechnik und örtlichem Klima.'],
        ['Kann KI im Kampf gegen den Klimawandel helfen?', 'Sie kann beitragen: Sie verbessert Wettervorhersagen, hilft beim Betrieb von Stromnetzen mit viel erneuerbarer Energie, senkt Energieverschwendung, beschleunigt die Forschung an neuen Materialien und ermöglicht es, Wälder, Eis und Emissionen per Satellit zu überwachen. Politische und wirtschaftliche Entscheidungen zur Emissionsminderung ersetzt sie nicht.'],
        ['Belastet die Nutzung eines Chatbots die Umwelt?', 'Jede Anfrage verbraucht eine kleine Menge Energie, die bei Milliarden von Nutzungen ins Gewicht fällt. Die tatsächliche Wirkung hängt vom Modell, von der Effizienz des Rechenzentrums und von der Energiequelle ab, die es versorgt.'],
        ['Wie werden KI-Rechenzentren mit Strom versorgt?', 'Mit Strom aus dem Netz, dessen Mix sich von Land zu Land unterscheidet. Große Unternehmen schließen Verträge über Solar-, Wind- und Kernenergie und bauen teils eigene Anlagen; wo das nicht reicht, kommt auch Gas zum Einsatz.']
      ]
    }
  }
};
